repos:
    - repo: https://github.com/google/yamlfmt
      rev: v0.17.0
      hooks:
        - id: yamlfmt
          args: ["-formatter", "indent=4"]
          exclude: charts/
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: requirements-txt-fixer
        - id: check-added-large-files
        - id: check-yaml
          args: ["--allow-multiple-documents"]
          exclude: charts/
