# app1 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: iot
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: hello-kubernetes
      # https://hub.docker.com/r/paulbouwer/hello-kubernetes/
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "This is App1!"
        - name: KUBERNETES_NAMESPACE
          value: "iot"
---
# app2 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: iot
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "This is App2!"
        - name: KUBERNETES_NAMESPACE
          value: "iot"
---
# app3 Deployment (default)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: iot
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "This is App3! (Default)"
        - name: KUBERNETES_NAMESPACE
          value: "iot"