apiVersion: apps/v1
kind: Deployment
metadata:
  name: inception-of-things
  namespace: inception-of-things
  labels:
    app: inception-of-things
    version: v1.0.0
    environment: production
    team: development
    project: inception-of-things
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inception-of-things
  template:
    metadata:
      labels:
        app: inception-of-things
    spec:
      containers:
      - image: containous/whoami:v1.5.0
        name: whoami