Vagrant.configure("2") do |config|
  username = `whoami`.strip

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.define "#{username}S" do |s|
    s.vm.hostname = "#{username}s"
    s.vm.box = "debian/bookworm64"
    s.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "#{username}SW" do |sw|
    sw.vm.hostname = "#{username}sw"
    sw.vm.box = "debian/bookworm64"
    sw.vm.network "private_network", ip: "192.168.56.111"
  end
end