# This is a Kubernetes Custom Resource of kind "Application", defined
# by Argo CD through a CRD (Custom Resource Definition).
# It allows GitOps-based deployment and tracking of applications from
# Git repositories.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: test-app
    namespace: argocd
spec:
    # The project the application belongs to.
    project: development
    # Source of the application manifests
    source:
        repoURL: https://github.com/yuuuuki15/playground.git
        targetRevision: test # For Helm, this refers to the chart version.
        path: manifests
    # Destination cluster and namespace to deploy the application
    destination:
        server: https://kubernetes.default.svc
        # name: in-cluster
        namespace: dev
    # Sync policy
    syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
            prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
            selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
            allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
